<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ticketflow</groupId>
        <artifactId>ticketflow</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ticketflow-redisson-framework</artifactId>
    <name>ticketflow-redisson-framework</name>
    <description>redisson封装</description>
    <packaging>pom</packaging>

    <modules>
        <module>ticketflow-service-delay-queue-framework</module>
        <module>ticketflow-redisson-service-framework</module>
    </modules>

</project>
