-- 在 ticketflow_order_0 库创建新表
USE ticketflow_order_0;
DROP TABLE IF EXISTS `d_order_4`;
CREATE TABLE d_order_4 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_5`;
CREATE TABLE d_order_5 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_6`;
CREATE TABLE d_order_6 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_7`;
CREATE TABLE d_order_7 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_ticket_user_4`;
CREATE TABLE d_order_ticket_user_4 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_5`;
CREATE TABLE d_order_ticket_user_5 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_6`;
CREATE TABLE d_order_ticket_user_6 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_7`;
CREATE TABLE d_order_ticket_user_7 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_4`;
CREATE TABLE d_order_ticket_user_record_4 LIKE d_order_ticket_user_record_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_5`;
CREATE TABLE d_order_ticket_user_record_5 LIKE d_order_ticket_user_record_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_6`;
CREATE TABLE d_order_ticket_user_record_6 LIKE d_order_ticket_user_record_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_7`;
CREATE TABLE d_order_ticket_user_record_7 LIKE d_order_ticket_user_record_0;

-- 在 ticketflow_order_1 库创建新表
USE ticketflow_order_1;
DROP TABLE IF EXISTS `d_order_4`;
CREATE TABLE d_order_4 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_5`;
CREATE TABLE d_order_5 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_6`;
CREATE TABLE d_order_6 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_7`;
CREATE TABLE d_order_7 LIKE d_order_0;
DROP TABLE IF EXISTS `d_order_ticket_user_4`;
CREATE TABLE d_order_ticket_user_4 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_5`;
CREATE TABLE d_order_ticket_user_5 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_6`;
CREATE TABLE d_order_ticket_user_6 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_7`;
CREATE TABLE d_order_ticket_user_7 LIKE d_order_ticket_user_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_4`;
CREATE TABLE d_order_ticket_user_record_4 LIKE d_order_ticket_user_record_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_5`;
CREATE TABLE d_order_ticket_user_record_5 LIKE d_order_ticket_user_record_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_6`;
CREATE TABLE d_order_ticket_user_record_6 LIKE d_order_ticket_user_record_0;
DROP TABLE IF EXISTS `d_order_ticket_user_record_7`;
CREATE TABLE d_order_ticket_user_record_7 LIKE d_order_ticket_user_record_0;